### ISSUE TITLE
请问  为什么手环连接后  过会会自动断开

### ISSUE THREAD

**Issue by 592713711** [pangliang/miband-sdk-android#11]
代码已经测试了   可以连接手环   一些功能可以实现   现在配对后手环不断开了  但是心跳测试还是失败，监听器一直没有数据

**Comment by pangliang** [comment]
你是否做过setUserInfo  ? 新版本不要设

**Comment by 592713711** [comment]
没有设置setUserInfo   请问你测试的时候是Android什么版本的？  sdk中扫描蓝牙的方式是需要api21以上的

**Comment by pangliang** [comment]
没记错应该是api 19吧?

**Comment by 592713711** [comment]
我的流程是  先miband.startScan扫描蓝牙设备， miband.connect连接扫描到的设备，连接成功后通过miband.pair绑定设备   震动、查看电池状态的功能可以实现    心跳检测时  miband.setHeartRateScanListener； miband.startHeartRateScan();执行后打印：
setCharacteristicNotification() - uuid: 00002a37-0000-1000-8000-00805f9b34fb enable: true
writeDescriptor() - uuid: 00002902-0000-1000-8000-00805f9b34fb
 writeCharacteristic() - uuid: 00002a39-0000-1000-8000-00805f9b34fb
onDescriptorWrite() - Device=C8:0F:10:37:7E:B2 UUID=00002a37-0000-1000-8000-00805f9b34fb

并没有收到手环响应信息，请问流程和打印的日志是否正确。

**Comment by pangliang** [comment]
呵呵，我觉得我应该吧pair去掉才对。
这个方法在之前也不知道是干啥用的。只不过查协议的时候发现这么个东西。
不做pair也可以执行其他操作的。

我那个demo里，操作列表，从上到下的测试顺序就对了。
我已经把setuserinfo和pair挪到最后了。

印象好像有过pair之后导致断线的问题，你试试

**Comment by pangliang** [comment]
1.1.02221306 版本修复
