### ISSUE TITLE
心跳測試的疑問

### ISSUE THREAD

**Issue by oilking143** [pangliang/miband-sdk-android#15]
按照您在2/22上面寫的範例
我使用了心跳檢測功能
但是輕拍了以後，雖然會震動，但是不會閃綠燈，而且掃出來的數值都是0

請問有解決方法嗎？

**Comment by pangliang** [comment]
有没有log 贴出来看看

**Comment by oilking143** [comment]
程式碼：

log就這樣
03-07 13:18:20.091 29908-30667/tw.com.acme_soft.mibandscanner D/miband-android: [0, 0, 0, 0]

看起來是有掃描到
但是沒抓到任何值

**Comment by pangliang** [comment]
你用我代码里的app测试, 在你的手环能跑通吗? 心跳是返回一个int, 不是返回4个元素的数组呢, 你是不是哪里搞错了

**Comment by oilking143** [comment]
是用原來的代碼沒錯
但是LOG不會跳出來

我把CODE寫在按鍵裡面：

     UserInfo userInfo = new UserInfo(20111111, 1, 32, 180, 55, "胖梁", 1);
                        mMiband.setUserInfo(userInfo);

                        mMiband.setHeartRateScanListener(new HeartRateNotifyListener() {
                            @Override
                            public void onNotify(int heartRate) {
                                Log.d(TAG, "heart rate: " + heartRate);
                            }
                        });

                        mMiband.startHeartRateScan();

是因為userInfo沒設定好？

**Comment by pangliang** [comment]
不要写到一个函数里; 分开做
这是两个步奏; setUserInfo 只需要做一次

**Comment by oilking143** [comment]
所以按鈕裡面只要startHeartRateScan();即可？

**Comment by oilking143** [comment]
自己找到答案了
要先start 再set listener的樣子

感謝梁大
