### ISSUE TITLE
请问重力感应原始数据获取现在是不是可以获取？

### ISSUE THREAD

**Issue by wly2014** [pangliang/miband-sdk-android#18]
您好，在使用您的sdk的时候发现，如果设置了实时传输步数的时候，如果中间稍微停顿了一下，再晃动手环，步数的数据不会再实时的更新，而是在大概持续10下之后，会继续更新。而且这个现象会同时在小米运动app上出现，也就可能是小米手环自身设置的问题。但是现在我希望能够检测到手环的实时振动，所以想知道是不是可以通过获取实时的重力感应数据来检测到手环发生了振动。
谢谢

**Comment by pangliang** [comment]
获取不了, 之前老版本的固件可以, 新版的官方改掉了; 而且现在官方app好像也没有这个"功能", 无法从官方app 反向出来

你有兴趣可以自己研究看看, 这里有反好的工程: https://github.com/pangliang/xiaomi-health-app-decompile
