### ISSUE TITLE
为什么每次设置userid,都会闪动并震动,需要拍下才行?而不是一样时候就无需配对?

### ISSUE THREAD

**Issue by kebbs** [pangliang/miband-sdk-android#19]
为什么每次设置userid,都会闪动并震动,需要拍下才行?而不是一样时候就无需配对?

**Comment by pangliang** [comment]
你确定userinfo 一样的时候需要拍, 不一样的时候不需要拍?

**Comment by kebbs** [comment]
谢谢,我今天测试可以了,相同的userid,第一次震动拍下确认后,就不需要拍了.
