### ISSUE TITLE
固件版本咨询

### ISSUE THREAD

**Issue by r17171709** [pangliang/miband-sdk-android#2]
你好，用你的代码，有没有手环固件版本限制。我现在最新版好像用你的代码只能获取到电池信息，其他好像都没有反应

**Comment by pangliang** [comment]
很多功能, 比如 震动, 设置led 什么的, 必须要先  setUserInfo

**Comment by r17171709** [comment]
但是我点击你设置的姓名什么的，只看到点击时候log，没执行什么回调啊

**Comment by pangliang** [comment]
setUserInfo 是没有回调的...

**Comment by pangliang** [comment]
readme 那有使用参考
