### ISSUE TITLE
[重力感應器功能詢問]

### ISSUE THREAD

**Issue by zhaoRuby** [pangliang/miband-sdk-android#3]
您好,想請問一下

在獲取重力感應器數據之前需要先設置什麼嗎?
已經設置好USERINFO、enableSensorDataNotify、setNormalNotifyListener
不過還是無法取得數據

謝謝您:D

**Comment by pangliang** [comment]
不对哈,setUserInfo -> setSensorDataListener -> enableSensorDataNNotify

**Comment by zhaoRuby** [comment]
好的！ 我再試試看。謝謝你

**Comment by pangliang** [comment]
我更新了readme, 可以参考看看, 实在不行, clone工程到本地,用studio打开,  app 模块是个demo

**Comment by j796160836** [comment]
您好，我照著sample
設置好setUserInfo -> setSensorDataListener -> enableSensorDataNNotify
還是無法取得數據？

**Comment by pangliang** [comment]
获取rssi 什么的正常吗?  setUserInfo 之后,  震动, 或者设置led颜色什么的是否可以用 ?
有些版本需要在小米健康那打开 蓝牙广播
