### ISSUE TITLE
报错: startLeScan() :null

### ISSUE THREAD

**Issue by wliment** [pangliang/miband-sdk-android#6]
后面还会报:
Caused by: java.lang.NullPointerException:
 Attempt to invoke virtual method 'android.bluetooth.BluetoothDevice android.bluetooth.BluetoothGatt.getDevice()' on a null object reference

貌似是蓝牙功能有问题,google 了半天没解决.

**Comment by pangliang** [comment]
BluetoothAdapter adapter = BluetoothAdapter.getDefaultAdapter();  这个adapter 是null  查下是不是加了访问蓝牙的权限

**Comment by wliment** [comment]
<uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>

蓝牙的访问权限一开始就已经添加到了AndroidManifest.xml. 问题依旧.

**Comment by wliment** [comment]
Class BluetoothIO   的connect 方法 adapter 获取的不是 null

**Comment by pangliang** [comment]
那你调试出来哪个变量是null ?

**Comment by wliment** [comment]
public BluetoothDevice getDevice()
	{
		return gatt.getDevice();
	}
	
里面的 gatt 为 null

估计是我设备的问题吧,关闭蓝牙的瞬间才能进入BluetoothIO.connect 里面的 onLeScan callback , 我换个小米的机子试试.

**Comment by pangliang** [comment]
哦, gatt 为null 就是没连上...  connect失败了
